= Using Spring Boot

The module `java-cfenv-boot` provides several `EnvironmentPostProcessor` implementations that set well known Boot properties so that Boot's auto-configuration can kick in.
For example, the `CfDataSourceEnvironmentPostProcessor` sets the Boot property `spring.datasource.url`.
Just add a dependency on `java-cfenv-boot`.

The list of supported services are:

== Databases - DB2, MySQL, Oracle, Postgresl, SqlServer
Properties that could be populated:

* `spring.datasource.url`
* `spring.datasource.username`
* `spring.datasource.password`
* `spring.datasource.driver-class-name`

== RabbitMQ
Properties that could be populated:

* `spring.rabbitmq.host`
* `spring.rabbitmq.username`
* `spring.rabbitmq.password`
* `spring.rabbitmq.ssl.enabled`
* `spring.rabbitmq.port`
* `spring.rabbitmq.virtualHost`
* `spring.rabbitmq.addresses`

`AmqpCfEnvProcessor` matches the Pivotal/Tanzu RabbitMQ tile: tags `rabbitmq` or `amqp`, a label that starts with `rabbitmq` or `cloudamqp`, or a top-level `uri`/`url` with an `amqp`/`amqps` scheme.

IBM Cloud Messages for RabbitMQ does not use that shape. The service label is `messages-for-rabbitmq` and the AMQPS URI sits under `credentials.connection.amqps` rather than a top-level `uri`. The built-in processor will not accept that binding.

[source,json]
----
{
  "label": "messages-for-rabbitmq",
  "credentials": {
    "connection": {
      "amqps": {
        "composed": ["amqps://user:pass@host:30301"],
        "authentication": { "username": "user", "password": "pass" },
        "hosts": [{ "hostname": "host", "port": 30301 }],
        "certificate": { "certificate_base64": "..." }
      }
    }
  }
}
----

Write a `CfEnvProcessor` whose `accept` method matches `messages-for-rabbitmq` (see the root README section on supporting other services). Read `connection.amqps.composed[0]`, or `hosts` plus `authentication`, and copy those values into `spring.rabbitmq.*`. The CA in `certificate.certificate_base64` is not installed by this library; load it into a trust store and set `spring.rabbitmq.ssl.trust-store`.

== Cassandra
Properties that could be populated:

* `spring.cassandra.username`
* `spring.cassandra.password`
* `spring.cassandra.port`
* `spring.cassandra.contact-points`

== MongoDB
Properties that could be populated:

* `spring.data.mongodb.uri`

== Redis

* `spring.data.redis.host`
* `spring.data.redis.password`
* `spring.data.redis.port`
* `spring.data.redis.ssl`

== CredHub
Properties that could be populated:

* `spring.credhub.url`
* `spring.credhub.oauth2`


== Hashicorp Vault
Properties that could be populated:

* `spring.cloud.vault.uri`
* `spring.cloud.vault.token`

== Notes

If, for any reason, you need to disable processing of a specific service instance, you can do so by setting the following flag in your application properties:
[source]
----
cfenv.service.{serviceName}.enabled=false
----

