---
jobs:
  - name: build-ci-images
    plan:
      - get: ci-images-git-repo
        trigger: true
      - put: java-cfenv-ci-image
        params:
          build: ci-images-git-repo/ci/images/java-cfenv-ci
        get_params:
          skip_download: "true"

  - name: build
    serial: true
    public: true
    plan:
      - in_parallel:
        - get: git-repo
          trigger: true
        - get: java-cfenv-ci-image
      - task: build-project
        image: java-cfenv-ci-image
        file: git-repo/ci/tasks/build-project.yml
      - put: artifactory-repo
        params: &artifactory-params
          signing_key: ((signing-key))
          signing_passphrase: ((signing-passphrase))
          repo: libs-snapshot-local
          folder: distribution-repository
          build_uri: "${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
          build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
          disable_checksum_uploads: true

  - name: stage-milestone
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          passed: [build]
        - get: java-cfenv-ci-image
      - task: stage
        image: java-cfenv-ci-image
        file: git-repo/ci/tasks/stage.yml
        vars:
          release-type: M
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: stage-rc
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          passed: [build]
        - get: java-cfenv-ci-image
      - task: stage
        image: java-cfenv-ci-image
        file: git-repo/ci/tasks/stage.yml
        vars:
          release-type: RC
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: stage-release
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          passed: [build]
        - get: java-cfenv-ci-image
      - task: stage
        image: java-cfenv-ci-image
        file: git-repo/ci/tasks/stage.yml
        vars:
          release-type: RELEASE
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: promote-milestone
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
        - get: artifactory-repo
          passed: [stage-milestone]
          params:
            save_build_info: true
        - get: concourse-release-scripts
      - task: promote
        image: concourse-release-scripts
        file: git-repo/ci/tasks/promote.yml
        vars:
          release-type: M

  - name: promote-rc
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
        - get: artifactory-repo
          passed: [stage-rc]
          params:
            save_build_info: true
        - get: concourse-release-scripts
      - task: promote
        image: concourse-release-scripts
        file: git-repo/ci/tasks/promote.yml
        vars:
          release-type: RC

  - name: promote-release
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
        - get: artifactory-repo
          passed: [stage-release]
          params:
            save_build_info: true
        - get: concourse-release-scripts
      - task: promote
        image: concourse-release-scripts
        file: git-repo/ci/tasks/promote.yml
        vars:
          release-type: RELEASE

  - name: sync-to-maven-central
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
        - get: artifactory-repo
          passed: [promote-release]
          params:
            save_build_info: true
        - get: concourse-release-scripts
      - task: sync-to-maven-central
        image: concourse-release-scripts
        file: git-repo/ci/tasks/sync-to-maven-central.yml

resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: ((corporate-harbor-registry))/((docker-hub-organization))/artifactory-resource
      password: ((corporate-harbor-robot-account.password))
      username: ((corporate-harbor-robot-account.username))
      tag: 0.0.14

resources:
  - name: git-repo
    type: git
    source:
      uri: ((java-cfenv-github-uri))
      branch: ((branch))
      ignore_paths: ["ci/images/*"]
      fetch_tags: true

  - name: git-repo-staging
    type: git
    source:
      uri: ((java-cfenv-github-uri))
      branch: ((github-username))/staging

  - name: ci-images-git-repo
    type: git
    source:
      uri: ((github-repo))
      branch: ((branch))
      paths: ["ci/images/*"]

  - name: java-cfenv-ci-image
    type: docker-image
    source:
      repository: ((corporate-harbor-registry))/((docker-hub-organization))/java-cfenv-ci
      username: ((corporate-harbor-robot-account.username))
      password: ((corporate-harbor-robot-account.password))

  - name: concourse-release-scripts
    type: registry-image
    source:
      repository: spring-scs-docker-virtual.usw1.packages.broadcom.com/ci/concourse-release-scripts
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: 0.4.2

  - name: artifactory-repo
    type: artifactory-resource
    source:
      uri: ((artifactory-server))
      username: ((scs-artifactory-username))
      password: ((scs-artifactory-password))
      build_name: ((build-name))

groups:
  - name: "build"
    jobs:
      - build
  - name: "milestone"
    jobs:
      - stage-milestone
      - promote-milestone
  - name: "rc"
    jobs:
      - stage-rc
      - promote-rc
  - name: "release"
    jobs:
      - stage-release
      - promote-release
      - sync-to-maven-central
  - name: "ci-images"
    jobs:
      - build-ci-images
